// sign up actions
export const SIGN_UP_ACTION = 'SIGN_UP_ACTION';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

// LOGIN ACTION
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// CREATE SCHEDULE
export const CREATE_SCHEDULE_ACTION = 'CREATE_SCHEDULE_ACTION';
export const CREATE_SCHEDULE_SUCCESSFUL = 'CREATE_SCHEDULE_SUCCESSFUL';
export const CREATE_SCHEDULE_FAILED = 'CREATE_SCHEDULE_FAILED';
